// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mage-study-go/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockperson creates a new instance of Mockperson. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockperson(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockperson {
	mock := &Mockperson{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockperson is an autogenerated mock type for the person type
type Mockperson struct {
	mock.Mock
}

type Mockperson_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockperson) EXPECT() *Mockperson_Expecter {
	return &Mockperson_Expecter{mock: &_m.Mock}
}

// BagItens provides a mock function for the type Mockperson
func (_mock *Mockperson) BagItens() []model.Item {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BagItens")
	}

	var r0 []model.Item
	if returnFunc, ok := ret.Get(0).(func() []model.Item); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}
	return r0
}

// Mockperson_BagItens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BagItens'
type Mockperson_BagItens_Call struct {
	*mock.Call
}

// BagItens is a helper method to define mock.On call
func (_e *Mockperson_Expecter) BagItens() *Mockperson_BagItens_Call {
	return &Mockperson_BagItens_Call{Call: _e.mock.On("BagItens")}
}

func (_c *Mockperson_BagItens_Call) Run(run func()) *Mockperson_BagItens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockperson_BagItens_Call) Return(items []model.Item) *Mockperson_BagItens_Call {
	_c.Call.Return(items)
	return _c
}

func (_c *Mockperson_BagItens_Call) RunAndReturn(run func() []model.Item) *Mockperson_BagItens_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Mockperson
func (_mock *Mockperson) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mockperson_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Mockperson_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Mockperson_Expecter) Name() *Mockperson_Name_Call {
	return &Mockperson_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Mockperson_Name_Call) Run(run func()) *Mockperson_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mockperson_Name_Call) Return(s string) *Mockperson_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mockperson_Name_Call) RunAndReturn(run func() string) *Mockperson_Name_Call {
	_c.Call.Return(run)
	return _c
}
